version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
  redis:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mexc:
    build: ./container-mexc
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
    - postgresdb